In [1]:
#!pip install keras

In [2]:
import pandas as pd
import numpy as np

In [3]:
#load data
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
concrete_data.shape

(1030, 9)

In [5]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [7]:
#split predictors and target
concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [8]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [9]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [10]:
#normalize data
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [11]:
n_cols = predictors_norm.shape[1] # number of predictors

In [12]:
import keras

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_squared_error'])
    return model

In [15]:
#split data train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3)

In [16]:
# build the model
model = regression_model()

In [17]:
# fit the model using data train
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
23/23 - 0s - loss: 1581.3545 - mean_squared_error: 1581.3545
Epoch 2/100
23/23 - 0s - loss: 1564.1554 - mean_squared_error: 1564.1554
Epoch 3/100
23/23 - 0s - loss: 1547.0836 - mean_squared_error: 1547.0836
Epoch 4/100
23/23 - 0s - loss: 1529.8461 - mean_squared_error: 1529.8461
Epoch 5/100
23/23 - 0s - loss: 1512.5312 - mean_squared_error: 1512.5312
Epoch 6/100
23/23 - 0s - loss: 1494.4423 - mean_squared_error: 1494.4423
Epoch 7/100
23/23 - 0s - loss: 1476.0238 - mean_squared_error: 1476.0238
Epoch 8/100
23/23 - 0s - loss: 1456.9258 - mean_squared_error: 1456.9258
Epoch 9/100
23/23 - 0s - loss: 1436.7305 - mean_squared_error: 1436.7305
Epoch 10/100
23/23 - 0s - loss: 1415.6438 - mean_squared_error: 1415.6438
Epoch 11/100
23/23 - 0s - loss: 1393.4451 - mean_squared_error: 1393.4451
Epoch 12/100
23/23 - 0s - loss: 1369.6833 - mean_squared_error: 1369.6833
Epoch 13/100
23/23 - 0s - loss: 1345.1093 - mean_squared_error: 1345.1093
Epoch 14/100
23/23 - 0s - loss: 1319.0780 - mean_squared_error: 1319.0780
Epoch 15/100
23/23 - 0s - loss: 1291.5190 - mean_squared_error: 1291.5190
Epoch 16/100
23/23 - 0s - loss: 1263.3077 - mean_squared_error: 1263.3077
Epoch 17/100
23/23 - 0s - loss: 1233.5552 - mean_squared_error: 1233.5552
Epoch 18/100
23/23 - 0s - loss: 1202.7334 - mean_squared_error: 1202.7334
Epoch 19/100
23/23 - 0s - loss: 1171.4408 - mean_squared_error: 1171.4408
Epoch 20/100
23/23 - 0s - loss: 1139.2645 - mean_squared_error: 1139.2645
Epoch 21/100
23/23 - 0s - loss: 1106.2213 - mean_squared_error: 1106.2213
Epoch 22/100
23/23 - 0s - loss: 1073.1698 - mean_squared_error: 1073.1698
Epoch 23/100
23/23 - 0s - loss: 1039.4125 - mean_squared_error: 1039.4125
Epoch 24/100
23/23 - 0s - loss: 1005.4736 - mean_squared_error: 1005.4736
Epoch 25/100
23/23 - 0s - loss: 971.9726 - mean_squared_error: 971.9726
Epoch 26/100
23/23 - 0s - loss: 938.2200 - mean_squared_error: 938.2200
Epoch 27/100
23/23 - 0s - loss: 904.0699 - mean_squared_error: 904.0699
Epoch 28/100
23/23 - 0s - loss: 871.1303 - mean_squared_error: 871.1303
Epoch 29/100
23/23 - 0s - loss: 838.1194 - mean_squared_error: 838.1194
Epoch 30/100
23/23 - 0s - loss: 805.3074 - mean_squared_error: 805.3074
Epoch 31/100
23/23 - 0s - loss: 773.9744 - mean_squared_error: 773.9744
Epoch 32/100
23/23 - 0s - loss: 742.7017 - mean_squared_error: 742.7017
Epoch 33/100
23/23 - 0s - loss: 712.8845 - mean_squared_error: 712.8845
Epoch 34/100
23/23 - 0s - loss: 683.1084 - mean_squared_error: 683.1084
Epoch 35/100
23/23 - 0s - loss: 654.7657 - mean_squared_error: 654.7657
Epoch 36/100
23/23 - 0s - loss: 627.1613 - mean_squared_error: 627.1613
Epoch 37/100
23/23 - 0s - loss: 600.7167 - mean_squared_error: 600.7167
Epoch 38/100
23/23 - 0s - loss: 575.3731 - mean_squared_error: 575.3731
Epoch 39/100
23/23 - 0s - loss: 551.1646 - mean_squared_error: 551.1646
Epoch 40/100
23/23 - 0s - loss: 528.0429 - mean_squared_error: 528.0429
Epoch 41/100
23/23 - 0s - loss: 505.8134 - mean_squared_error: 505.8134
Epoch 42/100
23/23 - 0s - loss: 485.0171 - mean_squared_error: 485.0171
Epoch 43/100
23/23 - 0s - loss: 465.6428 - mean_squared_error: 465.6428
Epoch 44/100
23/23 - 0s - loss: 446.6920 - mean_squared_error: 446.6920
Epoch 45/100
23/23 - 0s - loss: 429.4593 - mean_squared_error: 429.4593
Epoch 46/100
23/23 - 0s - loss: 412.8085 - mean_squared_error: 412.8085
Epoch 47/100
23/23 - 0s - loss: 397.6013 - mean_squared_error: 397.6013
Epoch 48/100
23/23 - 0s - loss: 382.9512 - mean_squared_error: 382.9512
Epoch 49/100
23/23 - 0s - loss: 369.4742 - mean_squared_error: 369.4742
Epoch 50/100
23/23 - 0s - loss: 356.7049 - mean_squared_error: 356.7049
Epoch 51/100
23/23 - 0s - loss: 344.7559 - mean_squared_error: 344.7559
Epoch 52/100
23/23 - 0s - loss: 333.2903 - mean_squared_error: 333.2903
Epoch 53/100
23/23 - 0s - loss: 323.1443 - mean_squared_error: 323.1443
Epoch 54/100
23/23 - 0s - loss: 313.3980 - mean_squared_error: 313.3980
Epoch 55/100
23/23 - 0s - loss: 304.2038 - mean_squared_error: 304.2038
Epoch 56/100
23/23 - 0s - loss: 295.8284 - mean_squared_error: 295.8284
Epoch 57/100
23/23 - 0s - loss: 287.8926 - mean_squared_error: 287.8926
Epoch 58/100
23/23 - 0s - loss: 280.4836 - mean_squared_error: 280.4836
Epoch 59/100
23/23 - 0s - loss: 273.3608 - mean_squared_error: 273.3608
Epoch 60/100
23/23 - 0s - loss: 266.7327 - mean_squared_error: 266.7327
Epoch 61/100
23/23 - 0s - loss: 260.3806 - mean_squared_error: 260.3806
Epoch 62/100
23/23 - 0s - loss: 254.6415 - mean_squared_error: 254.6415
Epoch 63/100
23/23 - 0s - loss: 248.9343 - mean_squared_error: 248.9343
Epoch 64/100
23/23 - 0s - loss: 243.9119 - mean_squared_error: 243.9119
Epoch 65/100
23/23 - 0s - loss: 238.8124 - mean_squared_error: 238.8124
Epoch 66/100
23/23 - 0s - loss: 234.1111 - mean_squared_error: 234.1111
Epoch 67/100
23/23 - 0s - loss: 229.5547 - mean_squared_error: 229.5547
Epoch 68/100
23/23 - 0s - loss: 225.4870 - mean_squared_error: 225.4870
Epoch 69/100
23/23 - 0s - loss: 221.2924 - mean_squared_error: 221.2924
Epoch 70/100
23/23 - 0s - loss: 217.7017 - mean_squared_error: 217.7017
Epoch 71/100
23/23 - 0s - loss: 214.1691 - mean_squared_error: 214.1691
Epoch 72/100
23/23 - 0s - loss: 210.7912 - mean_squared_error: 210.7912
Epoch 73/100
23/23 - 0s - loss: 207.6769 - mean_squared_error: 207.6769
Epoch 74/100
23/23 - 0s - loss: 204.7072 - mean_squared_error: 204.7072
Epoch 75/100
23/23 - 0s - loss: 201.8622 - mean_squared_error: 201.8622
Epoch 76/100
23/23 - 0s - loss: 199.2371 - mean_squared_error: 199.2371
Epoch 77/100
23/23 - 0s - loss: 196.6941 - mean_squared_error: 196.6941
Epoch 78/100
23/23 - 0s - loss: 194.3973 - mean_squared_error: 194.3973
Epoch 79/100
23/23 - 0s - loss: 192.0394 - mean_squared_error: 192.0394
Epoch 80/100
23/23 - 0s - loss: 189.8297 - mean_squared_error: 189.8297
Epoch 81/100
23/23 - 0s - loss: 187.8488 - mean_squared_error: 187.8488
Epoch 82/100
23/23 - 0s - loss: 185.8882 - mean_squared_error: 185.8882
Epoch 83/100
23/23 - 0s - loss: 183.9833 - mean_squared_error: 183.9833
Epoch 84/100
23/23 - 0s - loss: 182.2268 - mean_squared_error: 182.2268
Epoch 85/100
23/23 - 0s - loss: 180.4799 - mean_squared_error: 180.4799
Epoch 86/100
23/23 - 0s - loss: 178.8765 - mean_squared_error: 178.8765
Epoch 87/100
23/23 - 0s - loss: 177.2849 - mean_squared_error: 177.2849
Epoch 88/100
23/23 - 0s - loss: 175.7270 - mean_squared_error: 175.7270
Epoch 89/100
23/23 - 0s - loss: 174.2798 - mean_squared_error: 174.2798
Epoch 90/100
23/23 - 0s - loss: 172.7840 - mean_squared_error: 172.7840
Epoch 91/100
23/23 - 0s - loss: 171.4645 - mean_squared_error: 171.4645
Epoch 92/100
23/23 - 0s - loss: 170.1109 - mean_squared_error: 170.1109
Epoch 93/100
23/23 - 0s - loss: 168.8781 - mean_squared_error: 168.8781
Epoch 94/100
23/23 - 0s - loss: 167.5924 - mean_squared_error: 167.5924
Epoch 95/100
23/23 - 0s - loss: 166.4317 - mean_squared_error: 166.4317
Epoch 96/100
23/23 - 0s - loss: 165.2293 - mean_squared_error: 165.2293
Epoch 97/100
23/23 - 0s - loss: 164.0534 - mean_squared_error: 164.0534
Epoch 98/100
23/23 - 0s - loss: 162.9543 - mean_squared_error: 162.9543
Epoch 99/100
23/23 - 0s - loss: 161.8178 - mean_squared_error: 161.8178
Epoch 100/100
23/23 - 0s - loss: 160.7338 - mean_squared_error: 160.7338

In [18]:
# evaluate the model using data test
scores = model.evaluate(X_test, y_test, verbose=0)
print("MSE: {}".format(scores[0]))

MSE: 152.85354614257812

In [19]:
# evaluate the model using data test with sklearn 
from sklearn.metrics import mean_squared_error
y_pred= model.predict(X_test)

print("MSE: {}".format(mean_squared_error(y_test, y_pred)))

MSE: 152.85355311225413

In [20]:
#Repeat steps 1 - 3, 50 times, i.e., create a list of 50 mean squared errors.
MSE_scores=[]

for i in range(1,50):
        X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3) #split data
        model = regression_model()
        model.fit(X_train, y_train, epochs=100, verbose=0) #train model on training data using 50 epoc
        scores = model.evaluate(X_test, y_test, verbose=1)
        MSE_scores.append(scores[0])

10/10 [==============================] - 0s 2ms/step - loss: 73.2809 - mean_squared_error: 73.2809
10/10 [==============================] - 0s 666us/step - loss: 93.2187 - mean_squared_error: 93.2187
10/10 [==============================] - 0s 889us/step - loss: 112.7709 - mean_squared_error: 112.7709
10/10 [==============================] - 0s 667us/step - loss: 123.9436 - mean_squared_error: 123.9436
10/10 [==============================] - 0s 668us/step - loss: 89.3565 - mean_squared_error: 89.3565
10/10 [==============================] - 0s 667us/step - loss: 92.1086 - mean_squared_error: 92.1086
10/10 [==============================] - 0s 666us/step - loss: 104.5818 - mean_squared_error: 104.5818
10/10 [==============================] - 0s 732us/step - loss: 106.7417 - mean_squared_error: 106.7417
10/10 [==============================] - 0s 667us/step - loss: 83.8323 - mean_squared_error: 83.8323
10/10 [==============================] - 0s 666us/step - loss: 134.5763 - mean_squared_error: 134.5763
10/10 [==============================] - 0s 2ms/step - loss: 97.1901 - mean_squared_error: 97.1901
10/10 [==============================] - 0s 667us/step - loss: 707.0129 - mean_squared_error: 707.0129
10/10 [==============================] - 0s 1ms/step - loss: 118.8498 - mean_squared_error: 118.8498
10/10 [==============================] - 0s 2ms/step - loss: 96.9938 - mean_squared_error: 96.9938
10/10 [==============================] - 0s 2ms/step - loss: 353.6543 - mean_squared_error: 353.6543
10/10 [==============================] - 0s 601us/step - loss: 134.4952 - mean_squared_error: 134.4952
10/10 [==============================] - 0s 1ms/step - loss: 492.3125 - mean_squared_error: 492.3125
10/10 [==============================] - 0s 667us/step - loss: 111.7434 - mean_squared_error: 111.7434
10/10 [==============================] - 0s 1ms/step - loss: 235.4133 - mean_squared_error: 235.4133
10/10 [==============================] - 0s 1ms/step - loss: 116.3731 - mean_squared_error: 116.3731
10/10 [==============================] - 0s 995us/step - loss: 128.8886 - mean_squared_error: 128.8886
10/10 [==============================] - 0s 2ms/step - loss: 412.0627 - mean_squared_error: 412.0627
10/10 [==============================] - 0s 2ms/step - loss: 68.8815 - mean_squared_error: 68.8815
10/10 [==============================] - 0s 667us/step - loss: 111.6053 - mean_squared_error: 111.6053
10/10 [==============================] - 0s 779us/step - loss: 76.5403 - mean_squared_error: 76.5403
10/10 [==============================] - 0s 2ms/step - loss: 164.2053 - mean_squared_error: 164.2053
10/10 [==============================] - 0s 668us/step - loss: 329.4897 - mean_squared_error: 329.4897
10/10 [==============================] - 0s 665us/step - loss: 113.2188 - mean_squared_error: 113.2188
10/10 [==============================] - 0s 667us/step - loss: 87.7714 - mean_squared_error: 87.7714
10/10 [==============================] - 0s 667us/step - loss: 111.0367 - mean_squared_error: 111.0367
10/10 [==============================] - 0s 1ms/step - loss: 148.9003 - mean_squared_error: 148.9003
10/10 [==============================] - 0s 667us/step - loss: 148.6877 - mean_squared_error: 148.6877
10/10 [==============================] - 0s 2ms/step - loss: 117.9080 - mean_squared_error: 117.9080
10/10 [==============================] - 0s 745us/step - loss: 332.7718 - mean_squared_error: 332.7718
10/10 [==============================] - 0s 917us/step - loss: 118.8384 - mean_squared_error: 118.8384
10/10 [==============================] - 0s 668us/step - loss: 151.8705 - mean_squared_error: 151.8705
10/10 [==============================] - 0s 666us/step - loss: 259.5872 - mean_squared_error: 259.5872
10/10 [==============================] - 0s 1ms/step - loss: 159.3443 - mean_squared_error: 159.3443
10/10 [==============================] - 0s 666us/step - loss: 115.6881 - mean_squared_error: 115.6881
10/10 [==============================] - 0s 2ms/step - loss: 121.0116 - mean_squared_error: 121.0116
10/10 [==============================] - 0s 2ms/step - loss: 90.1756 - mean_squared_error: 90.1756
10/10 [==============================] - 0s 679us/step - loss: 555.8362 - mean_squared_error: 555.8362
10/10 [==============================] - 0s 1ms/step - loss: 96.2442 - mean_squared_error: 96.2442
10/10 [==============================] - 0s 2ms/step - loss: 119.6902 - mean_squared_error: 119.6902
10/10 [==============================] - 0s 556us/step - loss: 131.0748 - mean_squared_error: 131.0748
10/10 [==============================] - 0s 2ms/step - loss: 82.7168 - mean_squared_error: 82.7168
10/10 [==============================] - 0s 735us/step - loss: 110.2248 - mean_squared_error: 110.2248
10/10 [==============================] - 0s 778us/step - loss: 87.0604 - mean_squared_error: 87.0604
10/10 [==============================] - 0s 2ms/step - loss: 144.2609 - mean_squared_error: 144.2609

In [21]:
mean_MSE=np.mean(MSE_scores)
STD_MSE=np.std(MSE_scores)

#Report the mean and the standard deviation of the mean squared errors.
print('mean_MSE: {} \n STD_MSE: {}'.format(mean_MSE, STD_MSE))

mean_MSE: 166.81717401621293
 STD_MSE: 131.8878240664716

How does the mean of the mean squared errors compare to that from Step A?

In comparison with Part(B), mean and STD were decreased.